#!/bin/bash

function createOrg1() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/org1/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/org1/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:4400 --caname ca-org1 --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-4400-ca-org1.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-4400-ca-org1.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-4400-ca-org1.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-4400-ca-org1.pem
    OrganizationalUnitIdentifier: orderer' >${PWD}/organizations/peerOrganizations/org1/msp/config.yaml

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org1's CA cert to org1's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p ${PWD}/organizations/peerOrganizations/org1/msp/tlscacerts
  cp ${PWD}/organizations/fabric-ca/org1/ca-cert.pem ${PWD}/organizations/peerOrganizations/org1/msp/tlscacerts/ca.crt

  # Copy org1's CA cert to org1's /tlsca directory (for use by clients)
  mkdir -p ${PWD}/organizations/peerOrganizations/org1/tlsca
  cp ${PWD}/organizations/fabric-ca/org1/ca-cert.pem ${PWD}/organizations/peerOrganizations/org1/tlsca/tlsca.org1-cert.pem

  # Copy org1's CA cert to org1's /ca directory (for use by clients)
  mkdir -p ${PWD}/organizations/peerOrganizations/org1/ca
  cp ${PWD}/organizations/fabric-ca/org1/ca-cert.pem ${PWD}/organizations/peerOrganizations/org1/ca/ca.org1-cert.pem

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-org1 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-org1 --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-org1 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-org1 --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:4400 --caname ca-org1 -M ${PWD}/organizations/peerOrganizations/org1/peers/peer0.org1/msp --csr.hosts peer0.org1 --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:4400 --caname ca-org1 -M ${PWD}/organizations/peerOrganizations/org1/peers/peer1.org1/msp --csr.hosts peer1.org1 --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/org1/msp/config.yaml ${PWD}/organizations/peerOrganizations/org1/peers/peer0.org1/msp/config.yaml
  cp ${PWD}/organizations/peerOrganizations/org1/msp/config.yaml ${PWD}/organizations/peerOrganizations/org1/peers/peer1.org1/msp/config.yaml

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:4400 --caname ca-org1 -M ${PWD}/organizations/peerOrganizations/org1/peers/peer0.org1/tls --enrollment.profile tls --csr.hosts peer0.org1 --csr.hosts localhost --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null


  infoln "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:4400 --caname ca-org1 -M ${PWD}/organizations/peerOrganizations/org1/peers/peer1.org1/tls --enrollment.profile tls --csr.hosts peer1.org1 --csr.hosts localhost --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null

 # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp ${PWD}/organizations/peerOrganizations/org1/peers/peer0.org1/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/org1/peers/peer0.org1/tls/ca.crt
  cp ${PWD}/organizations/peerOrganizations/org1/peers/peer0.org1/tls/signcerts/* ${PWD}/organizations/peerOrganizations/org1/peers/peer0.org1/tls/server.crt
  cp ${PWD}/organizations/peerOrganizations/org1/peers/peer0.org1/tls/keystore/* ${PWD}/organizations/peerOrganizations/org1/peers/peer0.org1/tls/server.key

  cp ${PWD}/organizations/peerOrganizations/org1/peers/peer1.org1/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/org1/peers/peer1.org1/tls/ca.crt
  cp ${PWD}/organizations/peerOrganizations/org1/peers/peer1.org1/tls/signcerts/* ${PWD}/organizations/peerOrganizations/org1/peers/peer1.org1/tls/server.crt
  cp ${PWD}/organizations/peerOrganizations/org1/peers/peer1.org1/tls/keystore/* ${PWD}/organizations/peerOrganizations/org1/peers/peer1.org1/tls/server.key

  infoln "Generating the user msp"

  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:4400 --caname ca-org1 -M ${PWD}/organizations/peerOrganizations/org1/users/User1@org1/msp --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/org1/msp/config.yaml ${PWD}/organizations/peerOrganizations/org1/users/User1@org1/msp/config.yaml

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org1admin:org1adminpw@localhost:4400 --caname ca-org1 -M ${PWD}/organizations/peerOrganizations/org1/users/Admin@org1/msp --tls.certfiles ${PWD}/organizations/fabric-ca/org1/ca-cert.pem

  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/org1/msp/config.yaml ${PWD}/organizations/peerOrganizations/org1/users/Admin@org1/msp/config.yaml
}
function createOrg2() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/org2/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/org2/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:5500 --caname ca-org2 --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-5500-ca-org2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-5500-ca-org2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-5500-ca-org2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-5500-ca-org2.pem
    OrganizationalUnitIdentifier: orderer' >${PWD}/organizations/peerOrganizations/org2/msp/config.yaml

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org2's CA cert to org2's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p ${PWD}/organizations/peerOrganizations/org2/msp/tlscacerts
  cp ${PWD}/organizations/fabric-ca/org2/ca-cert.pem ${PWD}/organizations/peerOrganizations/org2/msp/tlscacerts/ca.crt

  # Copy org2's CA cert to org2's /tlsca directory (for use by clients)
  mkdir -p ${PWD}/organizations/peerOrganizations/org2/tlsca
  cp ${PWD}/organizations/fabric-ca/org2/ca-cert.pem ${PWD}/organizations/peerOrganizations/org2/tlsca/tlsca.org2-cert.pem

  # Copy org2's CA cert to org2's /ca directory (for use by clients)
  mkdir -p ${PWD}/organizations/peerOrganizations/org2/ca
  cp ${PWD}/organizations/fabric-ca/org2/ca-cert.pem ${PWD}/organizations/peerOrganizations/org2/ca/ca.org2-cert.pem

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-org2 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-org2 --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-org2 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-org2 --id.name org2admin --id.secret org2adminpw --id.type admin --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:5500 --caname ca-org2 -M ${PWD}/organizations/peerOrganizations/org2/peers/peer0.org2/msp --csr.hosts peer0.org2 --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:5500 --caname ca-org2 -M ${PWD}/organizations/peerOrganizations/org2/peers/peer1.org2/msp --csr.hosts peer1.org2 --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/org2/msp/config.yaml ${PWD}/organizations/peerOrganizations/org2/peers/peer0.org2/msp/config.yaml
  cp ${PWD}/organizations/peerOrganizations/org2/msp/config.yaml ${PWD}/organizations/peerOrganizations/org2/peers/peer1.org2/msp/config.yaml

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:5500 --caname ca-org2 -M ${PWD}/organizations/peerOrganizations/org2/peers/peer0.org2/tls --enrollment.profile tls --csr.hosts peer0.org2 --csr.hosts localhost --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null


  infoln "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:5500 --caname ca-org2 -M ${PWD}/organizations/peerOrganizations/org2/peers/peer1.org2/tls --enrollment.profile tls --csr.hosts peer1.org2 --csr.hosts localhost --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null

 # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp ${PWD}/organizations/peerOrganizations/org2/peers/peer0.org2/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/org2/peers/peer0.org2/tls/ca.crt
  cp ${PWD}/organizations/peerOrganizations/org2/peers/peer0.org2/tls/signcerts/* ${PWD}/organizations/peerOrganizations/org2/peers/peer0.org2/tls/server.crt
  cp ${PWD}/organizations/peerOrganizations/org2/peers/peer0.org2/tls/keystore/* ${PWD}/organizations/peerOrganizations/org2/peers/peer0.org2/tls/server.key

  cp ${PWD}/organizations/peerOrganizations/org2/peers/peer1.org2/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/org2/peers/peer1.org2/tls/ca.crt
  cp ${PWD}/organizations/peerOrganizations/org2/peers/peer1.org2/tls/signcerts/* ${PWD}/organizations/peerOrganizations/org2/peers/peer1.org2/tls/server.crt
  cp ${PWD}/organizations/peerOrganizations/org2/peers/peer1.org2/tls/keystore/* ${PWD}/organizations/peerOrganizations/org2/peers/peer1.org2/tls/server.key

  infoln "Generating the user msp"

  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:5500 --caname ca-org2 -M ${PWD}/organizations/peerOrganizations/org2/users/User1@org2/msp --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/org2/msp/config.yaml ${PWD}/organizations/peerOrganizations/org2/users/User1@org2/msp/config.yaml

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org2admin:org2adminpw@localhost:5500 --caname ca-org2 -M ${PWD}/organizations/peerOrganizations/org2/users/Admin@org2/msp --tls.certfiles ${PWD}/organizations/fabric-ca/org2/ca-cert.pem

  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/org2/msp/config.yaml ${PWD}/organizations/peerOrganizations/org2/users/Admin@org2/msp/config.yaml
}
function createOrderer1() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/itblanket.org/orderer1

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1


  fabric-ca-client enroll -u https://admin:adminpw@localhost:2200 --caname ca-orderer1 --tls.certfiles ${PWD}/organizations/fabric-ca/orderer1/ca-cert.pem


  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-2200-ca-orderer1.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-2200-ca-orderer1.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-2200-ca-orderer1.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-2200-ca-orderer1.pem
    OrganizationalUnitIdentifier: orderer' >${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/msp/config.yaml

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/orderer1/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/msp/tlscacerts/tlsca-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tlsca"
  cp "${PWD}/organizations/fabric-ca/orderer1/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tlsca/tlsca-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer1 --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles ${PWD}/organizations/fabric-ca/orderer1/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer1 --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles ${PWD}/organizations/fabric-ca/orderer1/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:2200 --caname ca-orderer1 -M ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/msp --tls.certfiles ${PWD}/organizations/fabric-ca/orderer1/ca-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/msp/config.yaml ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/msp/config.yaml

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:2200 --caname ca-orderer1 -M ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tls --enrollment.profile tls --csr.hosts orderer1 --csr.hosts localhost --tls.certfiles ${PWD}/organizations/fabric-ca/orderer1/ca-cert.pem
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tls/tlscacerts/* ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tls/ca.crt
  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tls/signcerts/* ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tls/server.crt
  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tls/keystore/* ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tls/server.key

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/msp/tlscacerts
  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/tls/tlscacerts/* ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/msp/tlscacerts/tlsca-cert.pem

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:2200 --caname ca-orderer1 -M ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/users/Admin@example.com/msp --tls.certfiles ${PWD}/organizations/fabric-ca/orderer1/tls-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/msp/config.yaml ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer1/users/Admin@example.com/msp/config.yaml
}
function createOrderer2() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/itblanket.org/orderer2

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2


  fabric-ca-client enroll -u https://admin:adminpw@localhost:2201 --caname ca-orderer2 --tls.certfiles ${PWD}/organizations/fabric-ca/orderer2/ca-cert.pem


  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-2201-ca-orderer2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-2201-ca-orderer2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-2201-ca-orderer2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-2201-ca-orderer2.pem
    OrganizationalUnitIdentifier: orderer' >${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/msp/config.yaml

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/orderer2/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/msp/tlscacerts/tlsca-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tlsca"
  cp "${PWD}/organizations/fabric-ca/orderer2/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tlsca/tlsca-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer2 --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles ${PWD}/organizations/fabric-ca/orderer2/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer2 --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles ${PWD}/organizations/fabric-ca/orderer2/ca-cert.pem
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:2201 --caname ca-orderer2 -M ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/msp --tls.certfiles ${PWD}/organizations/fabric-ca/orderer2/ca-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/msp/config.yaml ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/msp/config.yaml

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:2201 --caname ca-orderer2 -M ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tls --enrollment.profile tls --csr.hosts orderer2 --csr.hosts localhost --tls.certfiles ${PWD}/organizations/fabric-ca/orderer2/ca-cert.pem
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tls/tlscacerts/* ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tls/ca.crt
  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tls/signcerts/* ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tls/server.crt
  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tls/keystore/* ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tls/server.key

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/msp/tlscacerts
  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/tls/tlscacerts/* ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/msp/tlscacerts/tlsca-cert.pem

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:2201 --caname ca-orderer2 -M ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/users/Admin@example.com/msp --tls.certfiles ${PWD}/organizations/fabric-ca/orderer2/tls-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/msp/config.yaml ${PWD}/organizations/ordererOrganizations/itblanket.org/orderer2/users/Admin@example.com/msp/config.yaml
}


